import type { Metadata } from "next";
import "./globals.css";

import { inter, poppins } from "./theme/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "@splidejs/react-splide/css";
import "@splidejs/react-splide/css/core";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inter.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
